config/routes.rb
Rails.application.routes.draw do
  resources :maps
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/map.rb
class Map < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :set_map, only: [:show, :edit, :update, :destroy]

  # GET /maps
  # GET /maps.json
  def index
    @maps = Map.all
  end

  # GET /maps/1
  # GET /maps/1.json
  def show
  end

  # GET /maps/new
  def new
    @map = Map.new
  end

  # GET /maps/1/edit
  def edit
  end

  # POST /maps
  # POST /maps.json
  def create
    @map = Map.new(map_params)

    respond_to do |format|
      if @map.save
        format.html { redirect_to @map, notice: 'Map was successfully created.' }
        format.json { render :show, status: :created, location: @map }
      else
        format.html { render :new }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maps/1
  # PATCH/PUT /maps/1.json
  def update
    respond_to do |format|
      if @map.update(map_params)
        format.html { redirect_to @map, notice: 'Map was successfully updated.' }
        format.json { render :show, status: :ok, location: @map }
      else
        format.html { render :edit }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maps/1
  # DELETE /maps/1.json
  def destroy
    @map.destroy
    respond_to do |format|
      format.html { redirect_to maps_url, notice: 'Map was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_map
      @map = Map.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def map_params
      params.require(:map).permit(:nome_trecho, :numero_lei, :latitude_inicial, :longitude_inicial, :latitude_final, :longitude_final)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMapa</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/maps/_form.html.erb
<%= form_with(model: map, local: true) do |form| %>
  <% if map.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(map.errors.count, "error") %> prohibited this map from being saved:</h2>

      <ul>
        <% map.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome_trecho %>
    <%= form.text_field :nome_trecho %>
  </div>

  <div class="field">
    <%= form.label :numero_lei %>
    <%= form.text_field :numero_lei %>
  </div>

  <div class="field">
    <%= form.label :latitude_inicial %>
    <%= form.text_field :latitude_inicial %>
  </div>

  <div class="field">
    <%= form.label :longitude_inicial %>
    <%= form.text_field :longitude_inicial %>
  </div>

  <div class="field">
    <%= form.label :latitude_final %>
    <%= form.text_field :latitude_final %>
  </div>

  <div class="field">
    <%= form.label :longitude_final %>
    <%= form.text_field :longitude_final %>
  </div>

  <div id="mapid"></div>

  <div id="map">
    <%=
      map(:center => {
        :latlng => [51.52238797921441, -0.08366235665359283],
        :zoom => 18
      })
    %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/maps/edit.html.erb
<h1>Editing Map</h1>

<%= render 'form', map: @map %>

<%= link_to 'Show', @map %> |
<%= link_to 'Back', maps_path %>

app/views/maps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Maps</h1>

<table>
  <thead>
    <tr>
      <th>Nome trecho</th>
      <th>Numero lei</th>
      <th>Latitude inicial</th>
      <th>Longitude inicial</th>
      <th>Latitude final</th>
      <th>Longitude final</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @maps.each do |map| %>
      <tr>
        <td><%= map.nome_trecho %></td>
        <td><%= map.numero_lei %></td>
        <td><%= map.latitude_inicial %></td>
        <td><%= map.longitude_inicial %></td>
        <td><%= map.latitude_final %></td>
        <td><%= map.longitude_final %></td>
        <td><%= link_to 'Show', map %></td>
        <td><%= link_to 'Edit', edit_map_path(map) %></td>
        <td><%= link_to 'Destroy', map, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>


  </tbody>

</table>

<br>

<%= link_to 'New Map', new_map_path %>

app/views/maps/new.html.erb
<h1>New Map</h1>

<%= render 'form', map: @map %>

<%= link_to 'Back', maps_path %>

app/views/maps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome trecho:</strong>
  <%= @map.nome_trecho %>
</p>

<p>
  <strong>Numero lei:</strong>
  <%= @map.numero_lei %>
</p>

<p>
  <strong>Latitude inicial:</strong>
  <%= @map.latitude_inicial %>
</p>

<p>
  <strong>Longitude inicial:</strong>
  <%= @map.longitude_inicial %>
</p>

<p>
  <strong>Latitude final:</strong>
  <%= @map.latitude_final %>
</p>

<p>
  <strong>Longitude final:</strong>
  <%= @map.longitude_final %>
</p>

<%= link_to 'Edit', edit_map_path(@map) %> |
<%= link_to 'Back', maps_path %>